<e> ::= <prop> | <log>
<log> ::= and <e> <e> | not <e> | implies <e> <e> | since <e> <interval> <interval> <e> | once <e> <interval> <interval> | historically <e> <interval> <interval>
<prop> ::= proposition <var> <comp> <num>
<interval> ::= <dig>
<var> ::= LIT101 | MV101 | P101 | P102 | AIT202 | MV201 | P201 | P202 | P203 | P205 | DPIT301 | LIT301 | MV302 | MV303 | MV304 | P301 | P302 | AIT401 | AIT402 | FIT401 | LIT401 | P401 | P402 | UV401 | AIT502 | AIT504 | FIT501 | FIT502 | FIT504 | P501 | P502 | PIT501 | PIT502 | PIT503 | P601 | P602 | P603
<comp> ::= < | >
<num> ::= <dig> <dig>
<dig> ::= 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 0
